// 4320 Fuses:
// LP,XT,HS,EC,EC_IO,H4,RC_IO,INTRC_IO,INTRC,RC,
// FCMEN,NOFCMEN
// NOBROWNOUT,BROWNOUT,
// WDT1,WDT2,WDT4,WDT8,WDT16,WDT32,WDT64,WDT128,WDT256,WDT512,WDT1024,WDT2048,WDT4096,WDT8192,WDT16384,WDT32768,
// WDT,NOWDT,
// BORV20,BORV27,BORV42,BORV45,
// PUT,NOPUT,
// CPD,NOCPD,
// NOSTVREN,STVREN,
// NODEBUG,DEBUG,
// NOLVP,LVP,
// WRT,NOWRT,
// WRTD,NOWRTD,
// CCP2C1,CCP2B3,
// IESO,NOIESO,
// EBTR,NOEBTR,
// EBTRB,NOEBTRB,
// MCLR,NOMCLR,
// PROTECT,NOPROTECT,
// CPB,NOCPB,
// WRTB,NOWRTB
// WRTC,NOWRTC,
// PBADEN,NOPBADEN
#fuses INTRC_IO,NOFCMEN,NOBROWNOUT,WDT512,NOWDT,BORV20,NOPUT,NOCPD,STVREN,DEBUG,NOLVP,NOWRT,NOWRTD,CCP2B3,NOIESO,NOEBTR,MCLR,NOPROTECT,NOCPB,NOWRTB,NOWRTC,NOPBADEN

